import { Genres } from "./genres";

export interface Movie {
    id: number,
    adult?: boolean,
    backdrop_path?: string,
    belongs_to_collection?: Object,
    budget?: number,
    genres?: Array<Genres>,
    homepage?: string,
    imdb_id?: string,
    minLength?: number,
    maxLength?: number,
    pattern?: number,
    original_language?: string,
    original_title?: string,
    overview?: string,
    popularity?: number,
    poster_path?: string,
    production_companies?: Array<Object>,
    logo_path?: string,
    origin_country?: string,
    production_countries?: Array<Object>,
    release_date?: string
    format?: Date,
    revenue?: number,
    runtime?: number,
    spoken_languages?: Array<Object>,
    iso_639_1?: string,
    name?: string,
    status?: string,
    tagline?: string,
    title?: string,
    video?: boolean,
    vote_average?: number,
    vote_count?: number
}